#!/usr/bin/env zsh

# powerline10k

MY_PROMPT_CHAR='●•'

MY_PROMPT_CHAR_COLOR_INSERT_OK='blue'
MY_PROMPT_CHAR_COLOR_INSERT_ERROR='red'

MY_PROMPT_CHAR_COLOR_COMMAND='white'
MY_PROMPT_CHAR_COLOR_VISUAL='green'
MY_PROMPT_CHAR_COLOR_REPLACE='yellow'

MY_PROMPT_CONTEXT_COLOR='magenta'

MY_PROMPT_DIR_COLOR='cyan'

MY_PROMPT_GIT_COLOR_BRANCH='%4F'
MY_PROMPT_GIT_COLOR_TAG='%5F'
MY_PROMPT_GIT_COLOR_COMMIT='%3F'

MY_PROMPT_GIT_COLOR_BEHIND='%3F'
MY_PROMPT_GIT_COLOR_AHEAD='%2F'

MY_PROMPT_GIT_COLOR_STASHES='%5F'

MY_PROMPT_GIT_COLOR_CONFLICTED='%1F'

MY_PROMPT_GIT_COLOR_STAGED='%2F'
MY_PROMPT_GIT_COLOR_UNSTAGED='%3F'
MY_PROMPT_GIT_COLOR_UNTRACKED='%1F'

MY_PROMPT_AWS_COLOR_PROD='red'
MY_PROMPT_AWS_COLOR_TEST='yellow'
MY_PROMPT_AWS_COLOR_DEV='green'

MY_PROMPT_TIME_COLOR='magenta'

MY_PROMPT_STATUS_COLOR='black'

# fzf

MY_FZF_COLOR_DARK='bright-black'
MY_FZF_COLOR_HL='yellow'
MY_FZF_COLOR_LIGHT='white'
MY_FZF_COLOR_PROMPT='magenta'

MY_FZF_CHAR_MARKER='• '
MY_FZF_CHAR_POINTER='●'
MY_FZF_CHAR_PROMPT='●• '

