#!/usr/bin/env zsh

show() {
  bat --force-colorization --paging=never --plain "$1" || true # --terminal-width $(($2 - 2))
}

case "$1" in
  *.7z|*.iso|*.rar|*.zip)
    7z l -ba "$1" | tr -s ' ' | cut -d' ' -f6 | grep .
    ;;
  *.pdf)
    pdftotext "$1" -
    ;;
  *.tar*)
    tar -tf "$1"
    ;;
  *)
    MIME=$(file --brief --mime-type "$1")
    if [[ $MIME == text* || $MIME == *javascript || $MIME == *json ]]; then
      show "$1"
    elif [[ $MIME == 'inode/symlink' ]]; then
      show $(file --brief "$1" | sed -e 's/symbolic link to //')
    else
      file --brief "$1" | fold -w $(($2 - 2)) -s
    fi
    ;;
esac

